name: rainfall_qc
channels:
  - conda-forge
  - default
dependencies:
  - python>=3.10
  - numpy
  # Testing and development dependencies
  - black
  - coverage
  - flake8
  - bump-my-version==0.32.0
  - pre_commit
  - pylint
  - pip
  - pip:
      - ruff
      - pytest-cov
      - parameterized
