name: Run Python Tests
on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

permissions:
  contents: read
  pull-requests: read

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "pypy3.10", "3.10", "3.11", "3.12", "3.13" ]
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@cb605e52c26070c328afc4562f0b4ada7618a84e # v2.10.4
        with:
          egress-policy: audit

      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      # You can test your matrix by printing the current Python version
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
      - name: Run pytest coverage
        shell: bash -el {0}
        run: |
          python -m pytest --cov=./rainfallqc --cov-report xml
      - name: Lint with ruff
        uses: astral-sh/ruff-action@v3
        with:
          src: "./src"
      - name: Check format with ruff
        uses: astral-sh/ruff-action@v3
        with:
          args: "format --check"
      # - name: Coveralls GitHub Action
      #   uses: coverallsapp/github-action@648a8eb78e6d50909eff900e4ec85cab4524a45b # v2.3.6
      #   with:
      #     path-to-lcov: coverage.xml
